### ISSUE TITLE
Menu interactivity when settings are open.

### ISSUE THREAD

**Issue by KZeni** [corbindavenport/nimbus#6]
Isn't it weird that the top menu is still visible & interactive when the settings page is open, but it then doesn't do anything due to the settings being open? I was confused at first and then realized I had to press the button on the bottom right again for the navigation to become fully operational again. I'm sure I'm not alone in that confusion.

I see a few possible options:
- Make it so interacting with the top menu closes the settings page if open.
- Make it so the settings page is seen like the other pages so it's treated like swapping between the other pages.
- Make it so the navigation is swapped out to be a title bar that says something like "Settings" when settings are shown & swaps back to the navigation when closed.
- Make it so the top menu isn't visible when the settings are shown (leaving the bottom button as the only navigation item that then "returns" to the app).

**Comment by corbindavenport** [comment]
Actually Nimbus 2.0 fixes this by changing the navigation bar to the save button when settings is opened :)
